export const weatherConditions = {
  Rain: {
    color: '#11ffbd',
    color1: '#aaffa9',
    title: 'Raining',
    subtitle: 'Get a cup of coffee',
    icon: 'weather-rainy',
  },
  Clear: {
    color: '#f37335',
    color1: '#fdc830',
    title: 'So Sunny',
    subtitle: 'It is hurting my eyes',
    icon: 'weather-sunny',
  },
  Thunderstorm: {
    color: '#232526',
    color1: '#414345',
    title: 'A Storm is coming',
    subtitle: 'Because Gods are angry',
    icon: 'weather-lightning',
  },
  Clouds: {
    color: '#3e5151',
    color1: '#decba4',
    title: 'Clouds',
    subtitle: 'Everywhere',
    icon: 'weather-cloudy',
  },

  Snow: {
    color: '#c0c0aa',
    color1: '#1cefff',
    title: 'Snow',
    subtitle: 'Get out and build a snowman for me',
    icon: 'weather-snowy',
  },
  Drizzle: {
    color: '#182848',
    color1: '#4b6cb7',
    title: 'Drizzle',
    subtitle: 'Partially raining...',
    icon: 'weather-hail',
  },
  Haze: {
    color: '#0072ff',
    color1: '#00c6ff',
    title: 'Haze',
    subtitle: 'Another name for Partial Raining',
    icon: 'weather-hail',
  },
  Mist: {
    color: '#185a9d',
    color1: '#43cea2',
    title: 'Mist',
    subtitle: "Don't roam in forests!",
    icon: 'weather-fog',
  },
  Fog: {
    color: '#1f4037',
    color1: '#99f2c8',
    title: 'Mist',
    subtitle: "Don't roam in forests!",
    icon: 'weather-fog',
  },
};
